# Generated by Django 3.2.10 on 2022-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
