# Generated by Django 3.2 on 2021-07-29 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210729_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 23, 46, 43, 417592)),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
