# Generated by Django 3.2 on 2021-07-29 19:20

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0006_alter_product_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 50, 30, 562931)),
        ),
    ]
