# Generated by Django 3.2 on 2021-07-30 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210730_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 0, 14, 17, 218938)),
        ),
    ]
